{
 "title": "Monitoring Stack Overview",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Monitoring stack containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Grafana",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "management" },
     "expr": "count(container_tasks_state{name=\"grafana\", state=\"running\"}) OR on() vector(0)",
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "management" },
     "expr": "count(container_tasks_state{name=\"prometheus\", state=\"running\"}) OR on() vector(0)",
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Alert manager",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "management" },
     "expr": "count(container_tasks_state{name=\"alertmanager\", state=\"running\"}) OR on() vector(0)",
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "cAdvisor",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "management" },
     "expr": "count(container_tasks_state{name=\"cadvisor\", state=\"running\"}) OR on() vector(0)",
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "App",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "management" },
     "expr": "count(container_tasks_state{name=\"app\", state=\"running\"}) OR on() vector(0)",
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    }
   ]
  }
 ]
}